export const mockData = [
    { id: 1, name: 'Origin Energy', logo: '/images/deal4.jpeg', sales30Days: 120, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }, { name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 2, name: 'AGL', logo: '/images/deal4.jpeg', sales30Days: 85, sellableBrands: 'Deal Expert, Check Your Bill', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }, { name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 3, name: 'EnergyAustralia', logo: '/images/deal4.jpeg', sales30Days: 60, sellableBrands: 'Not Sellable', brands: [] },
    { id: 4, name: 'Ergon Energy', logo: '/images/deal4.jpeg', sales30Days: 45, sellableBrands: 'Check Your Bill', brands: [{ name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 5, name: 'Red Energy', logo: '/images/deal4.jpeg', sales30Days: 100, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 6, name: 'Alinta Energy', logo: '/images/deal4.jpeg', sales30Days: 70, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }] },
    { id: 7, name: 'ENGIE', logo: '/images/deal4.jpeg', sales30Days: 50, sellableBrands: 'Not Sellable', brands: [] },
    { id: 8, name: 'Aurora Energy', logo: '/images/deal4.jpeg', sales30Days: 90, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 9, name: 'Lumo Energy', logo: '/images/deal4.jpeg', sales30Days: 80, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 10, name: 'ActewAGL', logo: '/images/deal4.jpeg', sales30Days: 65, sellableBrands: 'Check Your Bill', brands: [{ name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 11, name: 'Momentum Energy', logo: '/images/deal4.jpeg', sales30Days: 55, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 12, name: 'Powershop', logo: '/images/deal4.jpeg', sales30Days: 95, sellableBrands: 'Deal Expert, Check Your Bill', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }, { name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 13, name: 'Dodo', logo: '/images/deal4.jpeg', sales30Days: 40, sellableBrands: 'Not Sellable', brands: [] },
    { id: 14, name: 'Sumo Power', logo: '/images/deal4.jpeg', sales30Days: 75, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }, { name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 15, name: 'Tango Energy', logo: '/images/deal4.jpeg', sales30Days: 85, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 16, name: 'GloBird Energy', logo: '/images/deal4.jpeg', sales30Days: 30, sellableBrands: 'Not Sellable', brands: [] },
    { id: 17, name: 'Locality Planning Energy', logo: '/images/deal4.jpeg', sales30Days: 20, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 18, name: '1st Energy', logo: '/images/deal4.jpeg', sales30Days: 110, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 19, name: 'Energy Locals', logo: '/images/deal4.jpeg', sales30Days: 105, sellableBrands: 'Check Your Bill', brands: [{ name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 20, name: 'Metered Energy', logo: '/images/deal4.jpeg', sales30Days: 95, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 21, name: 'Diamond Energy', logo: '/images/deal4.jpeg', sales30Days: 85, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }] },
    { id: 22, name: 'People Energy', logo: '/images/deal4.jpeg', sales30Days: 65, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 23, name: 'Enova Energy', logo: '/images/deal4.jpeg', sales30Days: 45, sellableBrands: 'Not Sellable', brands: [] },
    { id: 24, name: 'ReAmped Energy', logo: '/images/deal4.jpeg', sales30Days: 60, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 25, name: 'Qenergy', logo: '/images/deal4.jpeg', sales30Days: 75, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }] },
    { id: 26, name: 'Flow Systems', logo: '/images/deal4.jpeg', sales30Days: 85, sellableBrands: 'Check Your Bill', brands: [{ name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 27, name: 'OC Energy', logo: '/images/deal4.jpeg', sales30Days: 55, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 28, name: 'CovaU', logo: '/images/deal4.jpeg', sales30Days: 40, sellableBrands: 'Not Sellable', brands: [] },
    { id: 29, name: 'Arc Energy', logo: '/images/deal4.jpeg', sales30Days: 90, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 30, name: 'Mojo Power', logo: '/images/deal4.jpeg', sales30Days: 65, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }] },
    { id: 31, name: 'Winenergy', logo: '/images/deal4.jpeg', sales30Days: 55, sellableBrands: 'Check Your Bill', brands: [{ name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 32, name: 'Savant Energy', logo: '/images/deal4.jpeg', sales30Days: 70, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 33, name: 'Pooled Energy', logo: '/images/deal4.jpeg', sales30Days: 95, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 34, name: 'LPE', logo: '/images/deal4.jpeg', sales30Days: 60, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }, { name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 35, name: 'Glenergy', logo: '/images/deal4.jpeg', sales30Days: 75, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 36, name: 'Bright Spark Power', logo: '/images/deal4.jpeg', sales30Days: 85, sellableBrands: 'Compare Your Bills', brands: [{ name: 'Compare Your Bills', bgcolor: '#00afef' }] },
    { id: 37, name: 'BlueNRG', logo: '/images/deal4.jpeg', sales30Days: 95, sellableBrands: 'Check Your Bill', brands: [{ name: 'Check Your Bill', bgcolor: 'success.main' }] },
    { id: 38, name: 'Weston Energy', logo: '/images/deal4.jpeg', sales30Days: 55, sellableBrands: 'Not Sellable', brands: [] },
    { id: 39, name: 'ERM Power', logo: '/images/deal4.jpeg', sales30Days: 40, sellableBrands: 'Deal Expert', brands: [{ name: 'Deal Expert', bgcolor: 'primary.main' }] },
    { id: 40, name: 'Simply Energy', logo: '/images/deal4.jpeg', sales30Days: 70, sellableBrands: 'All', brands: [{ name: 'Deal Expert', bgcolor: '#040E8A' }, { name: 'Check Your Bill', bgcolor: '#0ea800' }] }
  ];